apiVersion: apps/v1
kind: Deployment
metadata:
  name: container2-deployment
  labels:
    app: container2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container2
  template:
    metadata:
      labels:
        app: container2
    spec:
      containers:
      - name: container2
        image: us-central1-docker.pkg.dev/kubernetes-assignment-428919/k8s-assignment/container2:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 6002
        volumeMounts:
        - name: persistent-storage
          mountPath: /shrey_PV_dir
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: k8s-volume
---
apiVersion: v1
kind: Service
metadata:
  name: container2-service
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 90
    targetPort: 6002
  selector:
    app: container2
